language: php

php:
- 7.4

services:
- docker

branches:
    only:
    - master

script:
    - mkdir -p vendor
    - docker-compose run --rm --user `id -u`:`id -g` composer install
    - docker-compose run --rm --user `id -u`:`id -g` test
